# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Article.delete_all
ActiveRecord::Base.connection.reset_pk_sequence!('articles')
Article.create(title: "super article", subtitle: "this is where i give slightly more information ", content: "Odd Future Godard Austin, crucifix brunch forage paleo. Try-hard freegan pug, Intelligentsia whatever wayfarers food truck normcore. Selfies fixie lo-fi, swag put a bird on it ugh irony aesthetic banjo tofu High Life pork belly. Scenester VHS twee, bespoke XOXO Brooklyn you probably haven't heard of them before they sold out. VHS Kickstarter ethical, Echo Park scenester PBR&B hoodie pork belly deep v banh mi art party occupy gastropub paleo. Austin next level leggings lomo, biodiesel you probably haven't heard of them four dollar toast kogi synth Banksy locavore Carles lo-fi hoodie. Paleo sartorial single-origin coffee, gentrify artisan aesthetic Bushwick kogi fap Carles sriracha flannel lo-fi cray.
Ethical authentic letterpress cray quinoa, Schlitz locavore organic flannel you probably haven't heard of them. IPhone flannel chia, fap roof party sriracha mixtape food truck. Fap tousled Intelligentsia, sriracha wolf lomo umami cliche polaroid. Lo-fi wolf biodiesel fingerstache. Keytar paleo tousled, typewriter High Life cornhole sriracha occupy cred fingerstache four dollar toast Brooklyn Vice actually. Bicycle rights selvage master cleanse small batch, Carles selfies Williamsburg tote bag asymmetrical hoodie chambray health goth YOLO. Pour-over High Life polaroid vinyl mustache direct trade, art party brunch yr letterpress viral lo-fi seitan organic bespoke.", image_one: "http://lorempixel.com/g/400/200/", image_two: "http://lorempixel.com/400/200/fashion", category: "Live", author: "jeff smith", social1_link: "https://twitter.com/pitchfork?lang=en-gb", social2_link: "https://www.facebook.com/james.bennett.3572", video_link: "https://www.youtube.com/watch?v=h2sfwky4RqQ", artist: 'Mozart parties')

Article.create(title: "super article", subtitle: "this is where i give slightly more information ", content: "Odd Future Godard Austin, crucifix brunch forage paleo. Try-hard freegan pug, Intelligentsia whatever wayfarers food truck normcore. Selfies fixie lo-fi, swag put a bird on it ugh irony aesthetic banjo tofu High Life pork belly. Scenester VHS twee, bespoke XOXO Brooklyn you probably haven't heard of them before they sold out. VHS Kickstarter ethical, Echo Park scenester PBR&B hoodie pork belly deep v banh mi art party occupy gastropub paleo. Austin next level leggings lomo, biodiesel you probably haven't heard of them four dollar toast kogi synth Banksy locavore Carles lo-fi hoodie. Paleo sartorial single-origin coffee, gentrify artisan aesthetic Bushwick kogi fap Carles sriracha flannel lo-fi cray.
Ethical authentic letterpress cray quinoa, Schlitz locavore organic flannel you probably haven't heard of them. IPhone flannel chia, fap roof party sriracha mixtape food truck. Fap tousled Intelligentsia, sriracha wolf lomo umami cliche polaroid. Lo-fi wolf biodiesel fingerstache. Keytar paleo tousled, typewriter High Life cornhole sriracha occupy cred fingerstache four dollar toast Brooklyn Vice actually. Bicycle rights selvage master cleanse small batch, Carles selfies Williamsburg tote bag asymmetrical hoodie chambray health goth YOLO. Pour-over High Life polaroid vinyl mustache direct trade, art party brunch yr letterpress viral lo-fi seitan organic bespoke.", image_one: "http://lorempixel.com/g/400/200/", image_two: "http://lorempixel.com/400/200/fashion", category: "Live", author: "jeff smith", social1_link: "https://twitter.com/pitchfork?lang=en-gb", social2_link: "https://www.facebook.com/james.bennett.3572", video_link: "https://www.youtube.com/watch?v=h2sfwky4RqQ", artist: 'Mozart parties')

Article.create(title: "super article", subtitle: "this is where i give slightly more information ", content: "Odd Future Godard Austin, crucifix brunch forage paleo. Try-hard freegan pug, Intelligentsia whatever wayfarers food truck normcore. Selfies fixie lo-fi, swag put a bird on it ugh irony aesthetic banjo tofu High Life pork belly. Scenester VHS twee, bespoke XOXO Brooklyn you probably haven't heard of them before they sold out. VHS Kickstarter ethical, Echo Park scenester PBR&B hoodie pork belly deep v banh mi art party occupy gastropub paleo. Austin next level leggings lomo, biodiesel you probably haven't heard of them four dollar toast kogi synth Banksy locavore Carles lo-fi hoodie. Paleo sartorial single-origin coffee, gentrify artisan aesthetic Bushwick kogi fap Carles sriracha flannel lo-fi cray.
Ethical authentic letterpress cray quinoa, Schlitz locavore organic flannel you probably haven't heard of them. IPhone flannel chia, fap roof party sriracha mixtape food truck. Fap tousled Intelligentsia, sriracha wolf lomo umami cliche polaroid. Lo-fi wolf biodiesel fingerstache. Keytar paleo tousled, typewriter High Life cornhole sriracha occupy cred fingerstache four dollar toast Brooklyn Vice actually. Bicycle rights selvage master cleanse small batch, Carles selfies Williamsburg tote bag asymmetrical hoodie chambray health goth YOLO. Pour-over High Life polaroid vinyl mustache direct trade, art party brunch yr letterpress viral lo-fi seitan organic bespoke.", image_one: "http://lorempixel.com/g/400/200/", image_two: "http://lorempixel.com/400/200/fashion", category: "Live", author: "jeff smith", social1_link: "https://twitter.com/pitchfork?lang=en-gb", social2_link: "https://www.facebook.com/james.bennett.3572", video_link: "https://www.youtube.com/watch?v=h2sfwky4RqQ", artist: 'Mozart parties')

Article.create(title: "super article", subtitle: "this is where i give slightly more information ", content: "Odd Future Godard Austin, crucifix brunch forage paleo. Try-hard freegan pug, Intelligentsia whatever wayfarers food truck normcore. Selfies fixie lo-fi, swag put a bird on it ugh irony aesthetic banjo tofu High Life pork belly. Scenester VHS twee, bespoke XOXO Brooklyn you probably haven't heard of them before they sold out. VHS Kickstarter ethical, Echo Park scenester PBR&B hoodie pork belly deep v banh mi art party occupy gastropub paleo. Austin next level leggings lomo, biodiesel you probably haven't heard of them four dollar toast kogi synth Banksy locavore Carles lo-fi hoodie. Paleo sartorial single-origin coffee, gentrify artisan aesthetic Bushwick kogi fap Carles sriracha flannel lo-fi cray.
Ethical authentic letterpress cray quinoa, Schlitz locavore organic flannel you probably haven't heard of them. IPhone flannel chia, fap roof party sriracha mixtape food truck. Fap tousled Intelligentsia, sriracha wolf lomo umami cliche polaroid. Lo-fi wolf biodiesel fingerstache. Keytar paleo tousled, typewriter High Life cornhole sriracha occupy cred fingerstache four dollar toast Brooklyn Vice actually. Bicycle rights selvage master cleanse small batch, Carles selfies Williamsburg tote bag asymmetrical hoodie chambray health goth YOLO. Pour-over High Life polaroid vinyl mustache direct trade, art party brunch yr letterpress viral lo-fi seitan organic bespoke.", image_one: "http://lorempixel.com/g/400/200/", image_two: "http://lorempixel.com/400/200/fashion", category: "Live", author: "jeff smith", social1_link: "https://twitter.com/pitchfork?lang=en-gb", social2_link: "https://www.facebook.com/james.bennett.3572", video_link: "https://www.youtube.com/watch?v=h2sfwky4RqQ", artist: 'Mozart parties')

Article.create(title: "super article", subtitle: "this is where i give slightly more information ", content: "Odd Future Godard Austin, crucifix brunch forage paleo. Try-hard freegan pug, Intelligentsia whatever wayfarers food truck normcore. Selfies fixie lo-fi, swag put a bird on it ugh irony aesthetic banjo tofu High Life pork belly. Scenester VHS twee, bespoke XOXO Brooklyn you probably haven't heard of them before they sold out. VHS Kickstarter ethical, Echo Park scenester PBR&B hoodie pork belly deep v banh mi art party occupy gastropub paleo. Austin next level leggings lomo, biodiesel you probably haven't heard of them four dollar toast kogi synth Banksy locavore Carles lo-fi hoodie. Paleo sartorial single-origin coffee, gentrify artisan aesthetic Bushwick kogi fap Carles sriracha flannel lo-fi cray.
Ethical authentic letterpress cray quinoa, Schlitz locavore organic flannel you probably haven't heard of them. IPhone flannel chia, fap roof party sriracha mixtape food truck. Fap tousled Intelligentsia, sriracha wolf lomo umami cliche polaroid. Lo-fi wolf biodiesel fingerstache. Keytar paleo tousled, typewriter High Life cornhole sriracha occupy cred fingerstache four dollar toast Brooklyn Vice actually. Bicycle rights selvage master cleanse small batch, Carles selfies Williamsburg tote bag asymmetrical hoodie chambray health goth YOLO. Pour-over High Life polaroid vinyl mustache direct trade, art party brunch yr letterpress viral lo-fi seitan organic bespoke.", image_one: "http://lorempixel.com/g/400/200/", image_two: "http://lorempixel.com/400/200/fashion", category: "Live", author: "jeff smith", social1_link: "https://twitter.com/pitchfork?lang=en-gb", social2_link: "https://www.facebook.com/james.bennett.3572", video_link: "https://www.youtube.com/watch?v=h2sfwky4RqQ", artist: 'Mozart parties')

Article.create(title: "super article", subtitle: "this is where i give slightly more information ", content: "Odd Future Godard Austin, crucifix brunch forage paleo. Try-hard freegan pug, Intelligentsia whatever wayfarers food truck normcore. Selfies fixie lo-fi, swag put a bird on it ugh irony aesthetic banjo tofu High Life pork belly. Scenester VHS twee, bespoke XOXO Brooklyn you probably haven't heard of them before they sold out. VHS Kickstarter ethical, Echo Park scenester PBR&B hoodie pork belly deep v banh mi art party occupy gastropub paleo. Austin next level leggings lomo, biodiesel you probably haven't heard of them four dollar toast kogi synth Banksy locavore Carles lo-fi hoodie. Paleo sartorial single-origin coffee, gentrify artisan aesthetic Bushwick kogi fap Carles sriracha flannel lo-fi cray.
Ethical authentic letterpress cray quinoa, Schlitz locavore organic flannel you probably haven't heard of them. IPhone flannel chia, fap roof party sriracha mixtape food truck. Fap tousled Intelligentsia, sriracha wolf lomo umami cliche polaroid. Lo-fi wolf biodiesel fingerstache. Keytar paleo tousled, typewriter High Life cornhole sriracha occupy cred fingerstache four dollar toast Brooklyn Vice actually. Bicycle rights selvage master cleanse small batch, Carles selfies Williamsburg tote bag asymmetrical hoodie chambray health goth YOLO. Pour-over High Life polaroid vinyl mustache direct trade, art party brunch yr letterpress viral lo-fi seitan organic bespoke.", image_one: "http://lorempixel.com/g/400/200/", image_two: "http://lorempixel.com/400/200/fashion", category: "Live", author: "jeff smith", social1_link: "https://twitter.com/pitchfork?lang=en-gb", social2_link: "https://www.facebook.com/james.bennett.3572", video_link: "https://www.youtube.com/watch?v=h2sfwky4RqQ", artist: 'Mozart parties')

Article.create(title: "super article", subtitle: "this is where i give slightly more information ", content: "Odd Future Godard Austin, crucifix brunch forage paleo. Try-hard freegan pug, Intelligentsia whatever wayfarers food truck normcore. Selfies fixie lo-fi, swag put a bird on it ugh irony aesthetic banjo tofu High Life pork belly. Scenester VHS twee, bespoke XOXO Brooklyn you probably haven't heard of them before they sold out. VHS Kickstarter ethical, Echo Park scenester PBR&B hoodie pork belly deep v banh mi art party occupy gastropub paleo. Austin next level leggings lomo, biodiesel you probably haven't heard of them four dollar toast kogi synth Banksy locavore Carles lo-fi hoodie. Paleo sartorial single-origin coffee, gentrify artisan aesthetic Bushwick kogi fap Carles sriracha flannel lo-fi cray.
Ethical authentic letterpress cray quinoa, Schlitz locavore organic flannel you probably haven't heard of them. IPhone flannel chia, fap roof party sriracha mixtape food truck. Fap tousled Intelligentsia, sriracha wolf lomo umami cliche polaroid. Lo-fi wolf biodiesel fingerstache. Keytar paleo tousled, typewriter High Life cornhole sriracha occupy cred fingerstache four dollar toast Brooklyn Vice actually. Bicycle rights selvage master cleanse small batch, Carles selfies Williamsburg tote bag asymmetrical hoodie chambray health goth YOLO. Pour-over High Life polaroid vinyl mustache direct trade, art party brunch yr letterpress viral lo-fi seitan organic bespoke.", image_one: "http://lorempixel.com/g/400/200/", image_two: "http://lorempixel.com/400/200/fashion", category: "Live", author: "jeff smith", social1_link: "https://twitter.com/pitchfork?lang=en-gb", social2_link: "https://www.facebook.com/james.bennett.3572", video_link: "https://www.youtube.com/watch?v=h2sfwky4RqQ", artist: 'Mozart parties')

Article.create(title: "super article", subtitle: "this is where i give slightly more information ", content: "Odd Future Godard Austin, crucifix brunch forage paleo. Try-hard freegan pug, Intelligentsia whatever wayfarers food truck normcore. Selfies fixie lo-fi, swag put a bird on it ugh irony aesthetic banjo tofu High Life pork belly. Scenester VHS twee, bespoke XOXO Brooklyn you probably haven't heard of them before they sold out. VHS Kickstarter ethical, Echo Park scenester PBR&B hoodie pork belly deep v banh mi art party occupy gastropub paleo. Austin next level leggings lomo, biodiesel you probably haven't heard of them four dollar toast kogi synth Banksy locavore Carles lo-fi hoodie. Paleo sartorial single-origin coffee, gentrify artisan aesthetic Bushwick kogi fap Carles sriracha flannel lo-fi cray.
Ethical authentic letterpress cray quinoa, Schlitz locavore organic flannel you probably haven't heard of them. IPhone flannel chia, fap roof party sriracha mixtape food truck. Fap tousled Intelligentsia, sriracha wolf lomo umami cliche polaroid. Lo-fi wolf biodiesel fingerstache. Keytar paleo tousled, typewriter High Life cornhole sriracha occupy cred fingerstache four dollar toast Brooklyn Vice actually. Bicycle rights selvage master cleanse small batch, Carles selfies Williamsburg tote bag asymmetrical hoodie chambray health goth YOLO. Pour-over High Life polaroid vinyl mustache direct trade, art party brunch yr letterpress viral lo-fi seitan organic bespoke.", image_one: "http://lorempixel.com/g/400/200/", image_two: "http://lorempixel.com/400/200/fashion", category: "Live", author: "jeff smith", social1_link: "https://twitter.com/pitchfork?lang=en-gb", social2_link: "https://www.facebook.com/james.bennett.3572", video_link: "https://www.youtube.com/watch?v=h2sfwky4RqQ", artist: 'Mozart parties')

Article.create(title: "super article", subtitle: "this is where i give slightly more information ", content: "Odd Future Godard Austin, crucifix brunch forage paleo. Try-hard freegan pug, Intelligentsia whatever wayfarers food truck normcore. Selfies fixie lo-fi, swag put a bird on it ugh irony aesthetic banjo tofu High Life pork belly. Scenester VHS twee, bespoke XOXO Brooklyn you probably haven't heard of them before they sold out. VHS Kickstarter ethical, Echo Park scenester PBR&B hoodie pork belly deep v banh mi art party occupy gastropub paleo. Austin next level leggings lomo, biodiesel you probably haven't heard of them four dollar toast kogi synth Banksy locavore Carles lo-fi hoodie. Paleo sartorial single-origin coffee, gentrify artisan aesthetic Bushwick kogi fap Carles sriracha flannel lo-fi cray.
Ethical authentic letterpress cray quinoa, Schlitz locavore organic flannel you probably haven't heard of them. IPhone flannel chia, fap roof party sriracha mixtape food truck. Fap tousled Intelligentsia, sriracha wolf lomo umami cliche polaroid. Lo-fi wolf biodiesel fingerstache. Keytar paleo tousled, typewriter High Life cornhole sriracha occupy cred fingerstache four dollar toast Brooklyn Vice actually. Bicycle rights selvage master cleanse small batch, Carles selfies Williamsburg tote bag asymmetrical hoodie chambray health goth YOLO. Pour-over High Life polaroid vinyl mustache direct trade, art party brunch yr letterpress viral lo-fi seitan organic bespoke.", image_one: "http://lorempixel.com/g/400/200/", image_two: "http://lorempixel.com/400/200/fashion", category: "Live", author: "jeff smith", social1_link: "https://twitter.com/pitchfork?lang=en-gb", social2_link: "https://www.facebook.com/james.bennett.3572", video_link: "https://www.youtube.com/watch?v=h2sfwky4RqQ", artist: 'Mozart parties')

Article.create(title: "super article", subtitle: "this is where i give slightly more information ", content: "Odd Future Godard Austin, crucifix brunch forage paleo. Try-hard freegan pug, Intelligentsia whatever wayfarers food truck normcore. Selfies fixie lo-fi, swag put a bird on it ugh irony aesthetic banjo tofu High Life pork belly. Scenester VHS twee, bespoke XOXO Brooklyn you probably haven't heard of them before they sold out. VHS Kickstarter ethical, Echo Park scenester PBR&B hoodie pork belly deep v banh mi art party occupy gastropub paleo. Austin next level leggings lomo, biodiesel you probably haven't heard of them four dollar toast kogi synth Banksy locavore Carles lo-fi hoodie. Paleo sartorial single-origin coffee, gentrify artisan aesthetic Bushwick kogi fap Carles sriracha flannel lo-fi cray.
Ethical authentic letterpress cray quinoa, Schlitz locavore organic flannel you probably haven't heard of them. IPhone flannel chia, fap roof party sriracha mixtape food truck. Fap tousled Intelligentsia, sriracha wolf lomo umami cliche polaroid. Lo-fi wolf biodiesel fingerstache. Keytar paleo tousled, typewriter High Life cornhole sriracha occupy cred fingerstache four dollar toast Brooklyn Vice actually. Bicycle rights selvage master cleanse small batch, Carles selfies Williamsburg tote bag asymmetrical hoodie chambray health goth YOLO. Pour-over High Life polaroid vinyl mustache direct trade, art party brunch yr letterpress viral lo-fi seitan organic bespoke.", image_one: "http://lorempixel.com/g/400/200/", image_two: "http://lorempixel.com/400/200/fashion", category: "Live", author: "jeff smith", social1_link: "https://twitter.com/pitchfork?lang=en-gb", social2_link: "https://www.facebook.com/james.bennett.3572", video_link: "https://www.youtube.com/watch?v=h2sfwky4RqQ", artist: 'Mozart parties')

Article.create(title: "super article", subtitle: "this is where i give slightly more information ", content: "Odd Future Godard Austin, crucifix brunch forage paleo. Try-hard freegan pug, Intelligentsia whatever wayfarers food truck normcore. Selfies fixie lo-fi, swag put a bird on it ugh irony aesthetic banjo tofu High Life pork belly. Scenester VHS twee, bespoke XOXO Brooklyn you probably haven't heard of them before they sold out. VHS Kickstarter ethical, Echo Park scenester PBR&B hoodie pork belly deep v banh mi art party occupy gastropub paleo. Austin next level leggings lomo, biodiesel you probably haven't heard of them four dollar toast kogi synth Banksy locavore Carles lo-fi hoodie. Paleo sartorial single-origin coffee, gentrify artisan aesthetic Bushwick kogi fap Carles sriracha flannel lo-fi cray.
Ethical authentic letterpress cray quinoa, Schlitz locavore organic flannel you probably haven't heard of them. IPhone flannel chia, fap roof party sriracha mixtape food truck. Fap tousled Intelligentsia, sriracha wolf lomo umami cliche polaroid. Lo-fi wolf biodiesel fingerstache. Keytar paleo tousled, typewriter High Life cornhole sriracha occupy cred fingerstache four dollar toast Brooklyn Vice actually. Bicycle rights selvage master cleanse small batch, Carles selfies Williamsburg tote bag asymmetrical hoodie chambray health goth YOLO. Pour-over High Life polaroid vinyl mustache direct trade, art party brunch yr letterpress viral lo-fi seitan organic bespoke.", image_one: "http://lorempixel.com/g/400/200/", image_two: "http://lorempixel.com/400/200/fashion", category: "Live", author: "jeff smith", social1_link: "https://twitter.com/pitchfork?lang=en-gb", social2_link: "https://www.facebook.com/james.bennett.3572", video_link: "https://www.youtube.com/watch?v=h2sfwky4RqQ", artist: 'Mozart parties')
